name: Mini Data CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9" 

    - name: Install dependencies
      run: pip install -r requirements.txt  

    - name: Run unit tests
      run: python -m unittest discover -s test -p "*.py"
